// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Iea2HmuJ07nbYmwC7oTKBcwp37So620',
    appId: '1:172910856288:web:69ecdad6c865f4ae2f9b05',
    messagingSenderId: '172910856288',
    projectId: 'uts-movie-app',
    authDomain: 'uts-movie-app.firebaseapp.com',
    storageBucket: 'uts-movie-app.firebasestorage.app',
    measurementId: 'G-WB51NDJKWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2hM0uF1HMbxIDHVqtIgGCHxnJX6IM33M',
    appId: '1:172910856288:android:ea25dc6dc68b556d2f9b05',
    messagingSenderId: '172910856288',
    projectId: 'uts-movie-app',
    storageBucket: 'uts-movie-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWVIvvDf5qhVQz8ZxRgpUaBcxyMD-Om-U',
    appId: '1:172910856288:ios:5da5d2420945c3262f9b05',
    messagingSenderId: '172910856288',
    projectId: 'uts-movie-app',
    storageBucket: 'uts-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.utsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWVIvvDf5qhVQz8ZxRgpUaBcxyMD-Om-U',
    appId: '1:172910856288:ios:5da5d2420945c3262f9b05',
    messagingSenderId: '172910856288',
    projectId: 'uts-movie-app',
    storageBucket: 'uts-movie-app.firebasestorage.app',
    iosBundleId: 'com.example.utsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Iea2HmuJ07nbYmwC7oTKBcwp37So620',
    appId: '1:172910856288:web:55a9027f120e51682f9b05',
    messagingSenderId: '172910856288',
    projectId: 'uts-movie-app',
    authDomain: 'uts-movie-app.firebaseapp.com',
    storageBucket: 'uts-movie-app.firebasestorage.app',
    measurementId: 'G-0CGH2LSBDH',
  );
}
// updateee
